WebUI/Controllers/ChefController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Repository;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.Infra;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class ChefController : Cruder<Chef, ChefInput>
    {
        private readonly IRepo<Chef> chefRepo;
        private readonly ICacheManager cache;

        public ChefController(ICrudService<Chef> service, IProMapper mapper, IRepo<Chef> chefRepo, ICacheManager cache)
            : base(service, mapper)
        {
            this.chefRepo = chefRepo;
            this.cache = cache;
        }

        protected override object MapEntityToGridModel(Chef chef)
        {
            return new { chef.Id, chef.FirstName, chef.LastName, Country = chef.Country.Name, chef.IsDeleted };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = chefRepo.GetAll(isAdmin).Where(o => o.FirstName.StartsWith(parent) || o.LastName.StartsWith(parent));

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
                OnCrud(ChangeType.Edit);
            }

            var model = new GridModelBuilder<Chef>(data.AsQueryable(), g)
                    {
                        Key = "Id",
                        Map = MapEntityToGridModel,
                        GetItem = () => chefRepo.Get(Convert.ToInt32(g.Key))
                    }.Build();

            return Json(model);
        }

        protected override void OnCrud(ChangeType chtype)
        {
            cache.ChangeAction<Chef>(chtype);
            base.OnCrud(chtype);
        }
    }
}

WebUI/Controllers/DinnerController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.Infra;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class DinnerController : Cruder<Dinner, DinnerInput>
    {
        private readonly ICacheManager cache;
        public DinnerController(ICrudService<Dinner> service, IProMapper mapper, ICacheManager cache)
            : base(service, mapper)
        {
            this.cache = cache;
        }

        protected override object MapEntityToGridModel(Dinner o)
        {
            return new
                {
                    o.Id, 
                    o.IsDeleted, 
                    o.Name,
                    CountryName = o.Country.Name,
                    ChefName = o.Chef.FirstName + " " + o.Chef.LastName,
                    o.Address,
                    MealsCount = o.Meals.Count
                };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.GetAll(isAdmin).Where(o => o.Name.Contains(parent));

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
                OnCrud(ChangeType.Edit);
            }

            var model = new GridModelBuilder<Dinner>(data, g)
                {
                    KeyProp = o => o.Id,
                    Map = MapEntityToGridModel,
                    GetItem = () => service.Get(Convert.ToInt32(g.Key))
                    
                }.Build();

            return Json(model);
        }

        public ActionResult Details(int key)
        {
            var dinner = service.Get(key);
            return PartialView(dinner);
        }

        protected override void OnCrud(ChangeType chtype)
        {
            cache.ChangeAction<Dinner>(chtype);
            base.OnCrud(chtype);
        }
    }
}

WebUI/Controllers/MealController.cs
using System;
using System.Web;
using System.Web.Mvc;
using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.Infra;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    public class MealController : Cruder<Meal, MealInput>
    {
        private new readonly IMealService service;
        private readonly IFileManagerService fileManagerService;
        private readonly ICacheManager cache;

        public MealController(IMealService service, IProMapper mapper, IFileManagerService fileManagerService, ICacheManager cache)
            : base(service, mapper)
        {
            this.service = service;
            this.fileManagerService = fileManagerService;
            this.cache = cache;
        }

        public ActionResult Grid()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetGridData(GridParams g, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.GetAll(isAdmin);

            if (restore.HasValue && isAdmin)
            {
                OnCrud(ChangeType.Edit);
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<Meal>(data, g)
            {
                KeyProp = o => o.Id,
                Map = o => new { o.Id, o.Name, o.Comments, o.Picture, o.IsDeleted },
                GetItem = () => service.Get(Convert.ToInt32(g.Key))
            }.Build();

            return Json(model);
        }

        public override ActionResult Index()
        {
            return View();
        }

        protected override string RowViewName => "ListItems/Meal";

        public ActionResult GetMeal(int id)
        {
            return Json(new { Id = id, Content = this.RenderPartialView(RowViewName, new[] { service.Get(id) }) });
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            int w, h;
            var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
            return Json(new { name, type = file.ContentType, size = file.ContentLength, w, h });
        }

        public ActionResult ChangePicture(int id, string gridId)
        {
            ViewData["gridId"] = gridId;
            return PartialView(service.Get(id));
        }

        [HttpPost]
        public ActionResult Crop(int x, int y, int w, int h, string filename, int id)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            OnCrud(ChangeType.Edit);
            return Json(new { name = filename });
        }

        protected override void OnCrud(ChangeType chtype)
        {
            cache.ChangeAction<Meal>(chtype);
            base.OnCrud(chtype);
        }

        #region used only by browsers that don't support drag and drop upload

        public ActionResult OChangePicture(int id)
        {
            return View(service.Get(id));
        }

        [HttpPost]
        public ActionResult OChangePicture()
        {
            var file = Request.Files["fileUpload"];
            var id = Convert.ToInt32(Request.Form["id"]);

            if (file.ContentLength > 0)
            {
                int w, h;
                var name = fileManagerService.SaveTempJpeg(Globals.PicturesPath, file.InputStream, out w, out h);
                return RedirectToAction("ocrop",
                                        new CropInput { ImageWidth = w, ImageHeight = h, Id = id, FileName = name });
            }

            return RedirectToAction("Index");
        }

        public ActionResult OCrop(CropInput cropDisplay)
        {
            return View(cropDisplay);
        }

        [HttpPost]
        public ActionResult OCrop(int x, int y, int w, int h, int id, string filename)
        {
            service.SetPicture(id, Globals.PicturesPath, filename, x, y, w, h);
            return RedirectToAction("ochangepicture", new { id });
        }

        #endregion
    }
}

WebUI/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using Omu.AwesomeMvc;
using Omu.ProDinner.Core.Model;
using Omu.ProDinner.Core.Service;
using Omu.ProDinner.WebUI.Mappers;
using Omu.ProDinner.WebUI.Utils;
using Omu.ProDinner.WebUI.ViewModels.Input;

namespace Omu.ProDinner.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Crudere<User, UserCreateInput, UserEditInput>
    {
        private new readonly IUserService service;

        public UserController(IProMapper mapper, IUserService service)
            : base(service, mapper)
        {
            this.service = service;
        }

        protected override object MapEntityToGridModel(User user)
        {
            return new
            {
                user.Id,
                user.IsDeleted,
                user.Login,
                Roles = string.Join(", ", user.Roles.Select(o => o.Name))
            };
        }

        [HttpPost]
        public ActionResult GridGetItems(GridParams g, string parent, bool? restore)
        {
            var isAdmin = WebUtils.IsUserAdmin();

            var data = service.GetAll(isAdmin).Where(o => o.Login.StartsWith(parent));

            if (restore.HasValue && isAdmin)
            {
                service.Restore(Convert.ToInt32(g.Key));
            }

            var model = new GridModelBuilder<User>(data.AsQueryable(), g)
            {
                Key = "Id",
                Map = MapEntityToGridModel,
                GetItem = () => service.Get(Convert.ToInt32(g.Key))
            }.Build();

            return Json(model);
        }

        public ActionResult ChangePassword(int id)
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordInput input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            service.ChangePassword(input.Id.Value, input.Password);

            return Json(new { Login = service.Get(input.Id.Value).Login });
        }
    }
}

WebUI/Views/Shared/ConfirmDelete.cshtml
@model DeleteConfirmInput
<div style="padding: 0 3em;">
    @using (Html.BeginForm())
    {
        @Html.Raw(Model.Message)
    }
    @*used by the popupform .OnLoad func*@
    <input type="hidden" name="key" value="@(Model.Id)" />
</div>

WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @ViewBag.Title - ProDinner ASP.net MVC Awesome Demo Application
    </title>
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    @{
        var settings = SettingsController.ReadSettings(HttpContext.Current.Request);
        var ver = 111;
    }
    <script>
        document.ver = @ver;
    </script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600|Roboto" rel="stylesheet">
    <link href="@Url.Content("~/Content/themes/" + settings.Theme + "/AwesomeMvc.css")?v=@ver" rel="stylesheet" type="text/css" id="aweStyle" />
    <link href="@Url.Content("~/Content/site.css")?v=@ver" rel="stylesheet" type="text/css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    @*jquery needs to be at the top (for document.ready $(function(){...})*@

    <script>
        var slinks = [
        { k: "@Url.Action("Index", "Chef")", c: "@Mui.Chef" },
        { k: "@Url.Action("Index", "Country")", c: "@Mui.Country" },
        { k: "@Url.Action("Index", "Dinner")", c: "Dinners" },
        { k: "@Url.Action("Index", "Feedback")", c: "Feedback" }
        ];
    </script>
</head>
<body class="@settings.Theme">
    <noscript>
        <div id="nos">
            this site works best with javascript allowed
        </div>
    </noscript>
    @(Html.Awe().InitPopup().Name("about")
            .Url(Url.Action("About", "Home"))
            .Modal()
            .LoadOnce()
            .Title("prodinner, where pros eat")
            .Mod(o => o.OutClickClose()))
    <div id="header">
        <nav class="cont" role="navigation">
            <ul class="menu">
                <li><a id='logo' href="@Url.Content("~")"><i></i></a></li>
                <li class="optional">@Html.ActionLink(Mui.Home, "Index", "Home")</li>
                <li>@Html.ActionLink(Mui.Meals, "Index", "Meal")</li>
                @if (WebUtils.IsUserAdmin())
                {
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                }
                <li>
                    @(Html.Awe().AjaxRadioList("ddlStuff")
                          .DataFunc("utils.getItems(slinks)")
                          .CssClass("nowave")
                          .MenuDropdown(o => o.Caption(Mui.Stuff).OpenOnHover()))
                </li>
                <li><a href="#" onclick="awe.open('about', { params: { anim: 'top fade' } }, event)">@Mui.About</a></li>
                @*anim 'top fade' in site.js 'aweopen' event handler*@
        </ul>
        <ul class="menu" style="float: right;">
            <li>@Html.Partial("login")</li>
        </ul>
    </nav>
</div>
@Html.Awe().InitPopup().Name("settings").Url(Url.Action("Index", "Settings")).LoadOnce().Width(100).Mod(o => o.Toggle().Dropdown())
<main id="main" class="cont">
    <div class="awe-il settings">
        <button type="button" class="awe-btn btnSettings" onclick="awe.open('settings', {}, event)"><span class="ico-settings">&nbsp;</span></button>
    </div>
    @RenderBody()
</main>
<footer id="footer">
    <nav class="cont" role="navigation">
        <div>download here: <a href='https://www.aspnetawesome.com'>https://www.aspnetawesome.com</a></div>
        <div>
            <a href="https://www.aspnetawesome.com/ContactUs">Contact Us</a>
            <a href="https://www.aspnetawesome.com/Company/TermsOfUse">Terms of Use</a>
            <a href="https://www.aspnetawesome.com/Company/PrivacyPolicy">Privacy policy</a>
        </div>
    </nav>
</footer>
@Html.Partial("doghelp")
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.1/js.cookie.min.js" type="text/javascript"></script>
@Scripts.Render("~/bundle/Scripts/js")

@*used in utils.init and sent on all post requests made by awe*@
@Html.AntiForgeryToken()

@Html.Awe().Init()

<script type="text/javascript">
    var root = '@(Url.Content("~"))';
    awem.clientDict = $.extend(awem.clientDict, @Html.Raw(Json.Encode(ClientSideUtils.GetClientDict())));
    awe.gmd = [awem.gridLoading, awem.gridPageInfo]; // set global grid mods

    var controller = '@(ViewContext.RouteData.Values["Controller"].ToString().ToLower())';
    var action = '@(ViewContext.RouteData.Values["Action"].ToString().ToLower())';
    $(function () {
        documentReady(root, controller, action);
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

WebUI/Views/Shared/deletebtn.cshtml
@model Omu.ProDinner.WebUI.ViewModels.Display.DelBtn
@if (Model.IsDeleted)
{
    <button type="button" class="awe-btn" onclick="awe.oc('restore@(Model.Name)', { params: { id: @(Model.Id) } })">
        <span class="ico-crud ico-restore"></span>
    </button>
}
else
{
    <button type="button" class="awe-btn" onclick="awe.open('delete@(Model.Name)', { params: { id: @(Model.Id) } }, event)">
        <span class="ico-crud ico-del"></span>
    </button>
}

WebUI/Views/Shared/doghelp.cshtml
<div id="tip">
    <div id="tipcontent">
        hi, click on the message to show more tips; click on me to hide
    </div>
</div>
<div id="dogh">
</div>

WebUI/Views/Shared/login.cshtml
@if (HttpContext.Current.User.Identity.IsAuthenticated)
{
    <span class="optional" style="vertical-align: middle;">Welcome</span>
    <span style="vertical-align: middle;">@HttpContext.Current.User.Identity.Name</span>
    @Html.ActionLink("Log out", "SignOff", "account")
}
else
{
    @Html.ActionLink("log in", "SignIn", "account")
}